import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";

// Use Inter as a fallback font
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

// Use the same font for mono
const interMono = Inter({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${interMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
